BEGIN TRANSACTION;
INSERT INTO `jacl2_rights` VALUES ('lizmap.repositories.view','__anonymous','fiji',0);
INSERT INTO `jacl2_rights` VALUES ('lizmap.repositories.view','admins','fiji',0);
INSERT INTO `jacl2_rights` VALUES ('lizmap.tools.displayGetCapabilitiesLinks','__anonymous','fiji',0);
INSERT INTO `jacl2_rights` VALUES ('lizmap.tools.displayGetCapabilitiesLinks','admins','fiji',0);
INSERT INTO `jacl2_rights` VALUES ('lizmap.tools.edition.use','__anonymous','fiji',0);
INSERT INTO `jacl2_rights` VALUES ('lizmap.tools.edition.use','admins','fiji',0);
INSERT INTO `jacl2_rights` VALUES ('lizmap.tools.layer.export','__anonymous','fiji',0);
INSERT INTO `jacl2_rights` VALUES ('lizmap.tools.layer.export','admins','fiji',0);
INSERT INTO `jacl2_rights` VALUES ('lizmap.tools.loginFilteredLayers.override','__anonymous','fiji',0);
INSERT INTO `jacl2_rights` VALUES ('lizmap.tools.loginFilteredLayers.override','admins','fiji',0);
COMMIT;
